on:
  push:
    branches:
      - master
name: release-please
jobs:
  continuous-integration:
    name: Continuous integration ${{ matrix.os }} python ${{ matrix.python-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",  "windows-latest"] #"macos-latest",
        python-version: ["3.7","3.8","3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Installing dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge numpy pandas geopandas pyproj shapley rasterio descartes matplotlib-base networkx scipy owslib tqdm map2model mplstereonet hjson loopprojectfile beartype cftime>=1.4.0-y
          
          
      - name: Checking formatting of code
        shell: bash -l {0}
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 map2loop --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 map2loop --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Building and install 
        shell: bash -l {0}
        run: |
          pip install .
#       - name: pytest
#         shell: bash -l {0}
#         run: |
#           pytest

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: python
          package-name: map2loop
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
